server:
  port: 8082

spring:
  application:
    name: payment-service

  datasource:
    url: jdbc:mysql://localhost:3306/microservices
    username: root
    password: Kumar@0224
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
